version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    groups:
      vercel:
        patterns:
          - "@vercel/*"
      chakra-ui:
        patterns:
          - "@chakra-ui/*"
      next-intl:
        patterns:
          - "next-intl"
          - "use-intl"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"