version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      vercel:
        patterns:
          - "@vercel/*"
      chakra-ui:
        patterns:
          - "@chakra-ui/*"
          - "@emotion/*"
      next:
        patterns:
          - "next"
          - "next-intl"
          - "next-themes"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      trpc:
        patterns:
          - "@trpc/*"
          - "@tanstack/react-query"
      devtools:
        patterns:
          - "@eslint/eslintrc"
          - "eslint"
          - "eslint-config-next"
          - "jest"
          - "@types/jest"
          - "jest-environment-jsdom"
          - "typescript-eslint"
          - "prettier"
      other:
        patterns:
          - "*"
