---
name: "Request additional CSS styles"
description: "Request a new CSS selector or property to be added to the designer"
labels: "Style+Request"
body:
- type: markdown
  attributes:
    value: Before you request a new CSS selector or property to be added, search through the existing issues to see if others have had the same idea.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: This issue is not a duplicate of [previous requests](https://github.com/shadow578/m365-custom-css-designer/issues?q=is%3Aissue+label%3A%22Style+Request%22+).
        required: true

- type: textarea
  attributes:
    label: "Provide the details of the CSS selector or property you would like to see added"
    description: "Explain what the CSS selector or property is, how it should be used, and why it would be beneficial to have it in the designer. For new selectors, provide the properties you think should be designable."
    placeholder: |
      '.ext-background-overlay' selects the overlay over the background of the sign-in page. it'd be nice to style it to change the color of the overlay (via the 'background-color' property).
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the feature request here. Screenshots of your suggestion in action are appreciated."
  validations:
    required: true