# CD workflow for vercel deployment (unified for prod and preview)
# see: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions: {}

jobs:
  deploy:
    name: "Deploy to Vercel"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only if CI passed
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: npm install --global vercel@latest

      - name: "Deploy to Vercel (Preview)"
        if: github.event.workflow_run.head_branch != 'main'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: "Deploy to Vercel (Production)"
        if: github.event.workflow_run.head_branch == 'main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
